# config.yaml

[cameras] # section-header ignored by configargparse
amscope_mu1804: {
   color_format: RGB,
   color_depth: 8,
   snapshot: {
      sizes: [large, medium, small],
      size: {
        large: [ 3684, 4912 ],
        medium: [ 1842, 2456 ],
        small: [ 922, 1228 ],
        default: large,
        }
     },
   video: {
     sizes: [ large, medium, small ],
      size: {
        large: [ 3684, 4912 ],
        medium: [ 1842, 2456 ],
        small: [ 922, 1228 ],
        default: large,
        }
     },
   pixel_dimensions:{
      olympus_bx41: {
        camera_image_sizes: [ large, medium, small ],
        camera_calibration_for_image_size: {
          large: {
            pixels_per_millimeter_at_mag: {
              2: 1605,
              4: 3209,
              10: 8051,
              20: 16232,
              60: 48405,
              },
            microns_per_pixel_at_mag: {
              2: 0.623,
              4: 0.312,
              10: 0.124,
              20: 0.062,
              60: 0.021,
              },
            },
          },
        units: micrometer,
        microns_per_pixel: {
          image_size_large: {
            2x: 0.623,
            4x: 0.312,
            10x: 0.124,
            20x: 0.062,
            60x: 0.021,
            },
          image_size_medium: {
            2x: 1.246,
            4x: 0.623,
            10x: 0.312,
            20x: 0.124,
            60x: 0.042,
            },
          image_size_small: {},
          },
        }
     }
  }

[whole_slide_images] # section-header ignored by configargparse
# NOTE: the following Philips_exported_tiff data comes from a test Philips slide 1.isyntax (export ?and ObjectiveConvert)
#   D:\Whole_Slide\Philips\Philips_Test_Slides\1_BIG_sparse.tiff
philips_exported_tiff: {
  scan_magnifications: [ 40, 20, 10, 5, 2.5, 1.25, 0.0625 ],
  default_scan_magnification: 40,
  pixel_width_unit: micrometer,
  pixel_width_at_mag: {
    40: 0.25,
    20: 0.5,
    10: 1.0,
    5: 2.0,
    2.5: 4.0,
    1.25: 8.0,
    0.0625: 16.0,
    default: 0.25,
    },
  tiffinfo: {
     tile_width: [512, 512],
     bits_per_sample: 8,
     compression_scheme: JPEG,
     compression_quality: unknown,
     photometric_interpretation: YCbCr,
     ycbcr_subsampling: [2, 2],
     oientation: row 0 top, col 0 lhs,
     planar_configuration: single image plane
      }
  }


[microscopes] # section-header ignored by configargparse
olympus_bx41: {
  ocular_magnification: 10,
  objective_magnifications: [40, 20, 10,4, 2],
  }
